### ISSUE TITLE
Running "htmlmin:dist" (htmlmin) task freezes

### ISSUE THREAD

**Issue by invinciblemuffi** [gruntjs/grunt-contrib-htmlmin#116]
Running "htmlmin:dist" (htmlmin) task freezes when I run it in command line.
My task configuration is as follows: 
    htmlmin: {                                     // Task
        dist: {                                      // Target
          options: {                                 // Target options
        	  removeComments: true,
              collapseWhitespace: true,
              removeEmptyAttributes: true,
              removeCommentsFromCDATA: true,
              removeRedundantAttributes: true,
              collapseBooleanAttributes: true
          },
          files: [
                  {                                   
                	  expand: true,
                	  cwd: '<%= cwdPath %>',
                	  src: [ '**/*.html', '!index-requirejs.html', '!online/**/*.html' ], 
                	  dest: '<%= destPath %>min/'
                  }
             ]
        }
      }

**Comment by Kuzmin** [comment]
It's weird, I never had issues with this before, and this issue just occured to me too, for the first time, yesterday. And I haven't changed anything in my config or so, it seems like it just randomly froze..

**Comment by invinciblemuffi** [comment]
I tried executing it several times yesterday, files are properly minified
and generated as per the config, but frm cmd line the execution of that
task seems not to complete itself. Could anyone look into this.

**Comment by rgolea** [comment]
I have the same issue here... Does anyone have any idea of what's going on?

**Comment by Kuzmin** [comment]
Alright so I debugged this a bit further. For me, my issue was actually that I had a file with invalid HTML in it, and for some reason, htmlmin hanged there and didn't continue processing...

I guess you guys (@rgolea  and @invinciblemuffi) could see if you have similar problems? I ran `grunt htmlmin:dist --verbose` and that outputted all the files read and minifed. If you had the same issue as me, you should see that the command freezes on a certain file each time. Check the file for syntax errors and see if that resolves the problem?

As for this bug, I'm not sure about how to solve this since the minify call here just freezes:

```      
try {
    min = minify(max, options);
} catch (err) {
    grunt.warn(src + '\n' + err);
    return;
}
```

The ideal solution would be that the plugin warned when a file is malformed, but since minify() doesn't, I'm not sure how grunt-contrib-htmlmin would.. Maybe wrapping it in a timer that outputs the filename of the broken file after five seconds or so? I could make a PR for that. Not sure that's optimal but at least it fixes this... (I guess the real solution would be to patch minify() so that it prints an error, but that feels like a bigger project.) 

Would a PR for this be accepted? ping @sindresorhus @shama :)

**Comment by sindresorhus** [comment]
Should be fixed in https://github.com/kangax/html-minifier.

**Comment by Kuzmin** [comment]
@sindresorhus Alright, thank you! :)

**Comment by invinciblemuffi** [comment]
@Kuzmin: Thank you for the help and to share the knowledge on how to debug it further.
